baseURL = 'https://3161-187-191-11-171.ngrok.io'
title        = "My Podcast"
languageCode = "en-us"
theme        = "hello-4s3ti"
paginate     = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"


  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Blog de Making Devs"
  keywords = "Podcast"
  images = ["/themes/hello-4s3ti/images/logoMD.png"]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Viva Código"
    subtitle = ""
    keywords = "Podcast"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "LEER OTRAS PUBLICACIONES"

    [languages.en.params.logo]
      logoText = "Vive Código - Podcast"
      logoHomeLink = "/posts"
    # or
    #
    # path = "/posts"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Podcast"
    url        = "/posts"
